---
comments:
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

naming:
  FunctionNameMaxLength:
    excludes: [ '**/test/**', '**/*Test/**' ]

potential-bugs:
  ImplicitUnitReturnType:
    excludes: [ '**/test/**', '**/*Test/**' ]
  UnnamedParameterUse:
    active: false

style:
  UnnecessaryApply:
    active: false
  MultilineRawStringIndentation:
    active: false
  RedundantVisibilityModifier:
    active: false
