name: ktlint

on:
  pull_request:
    paths:
      - "**.kt"
      - "**.kts"

permissions:
  contents: read

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache ktlint
        uses: actions/cache@v5
        with:
          path: /usr/local/bin/ktlint
          key: ktlint-1.8.0

      - name: Install ktlint
        run: |
          if [ ! -f /usr/local/bin/ktlint ]; then
            curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.8.0/ktlint
            chmod a+x ktlint
            sudo mv ktlint /usr/local/bin/
          fi

      - name: Run ktlint
        run: scripts/ktlintCheck.sh
